name: "CI"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        node-version: [18.x]
        go-version: ["1.22"]

    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: "Install the dependencies"
        run: "npm install"

      - name: Hardhat coverage
        run: |
          npx hardhat coverage

      - name: "Run linter"
        run: "npm run lint"
