// SPDX-License-Identifier: MIT

/* AUTOGENERATED FILE BY HARDHAT-ZKIT. DO NOT EDIT. */

pragma solidity >=0.7.0 <0.9.0;

contract EmployeeDataGroth16Verifier {
    // @dev scalar field size
    uint256 public constant SCALAR_FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    /// @dev base field size
    uint256 public constant BASE_FIELD_SIZE =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev verification key data
    uint256 public constant ALPHA_X =
        20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 public constant ALPHA_Y =
        9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 public constant BETA_X1 =
        4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 public constant BETA_X2 =
        6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 public constant BETA_Y1 =
        21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 public constant BETA_Y2 =
        10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 public constant GAMMA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant GAMMA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant GAMMA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant GAMMA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 public constant DELTA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant DELTA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant DELTA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant DELTA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;

    uint256 public constant IC0_X =
        5441143704941414777545769957436946473945051050557952290999314272932261584097;
    uint256 public constant IC0_Y =
        1654427268763629977380410910250866469880092964385955530864955129216556811979;
    uint256 public constant IC1_X =
        13159781182402429898669290653441495588338328897221569963298105697355578406705;
    uint256 public constant IC1_Y =
        21150799594214784641395368559898581501183631893053172652600151699436296492619;
    uint256 public constant IC2_X =
        11819988983724988231011059771053095818238579951215225783859289067524775791461;
    uint256 public constant IC2_Y =
        12540642408608911820454467456542739884751959200507184354117835180474720260994;
    uint256 public constant IC3_X =
        4271886760387915850952459696995119858149686021668243997915389933685523158958;
    uint256 public constant IC3_Y =
        14868566138436675109407193778526076282558875552358260068894671732732710306523;
    uint256 public constant IC4_X =
        4444502273640348524943870023700636206138422269008665188712405041619847897345;
    uint256 public constant IC4_Y =
        11190593048095367693814881532272099226534075921243760389641836111627626755131;
    uint256 public constant IC5_X =
        19077331900780125812050816870949286633246874017656583623854719837197318161776;
    uint256 public constant IC5_Y =
        15284648105395003829106948012356112119753236317370570954260070634618241603920;
    uint256 public constant IC6_X =
        11837803739157261199436139794717090797546815223389829819594210938551648780373;
    uint256 public constant IC6_Y =
        10710284387028497062180154203135478834398441863070180424469702457621366198149;
    uint256 public constant IC7_X =
        15237349388245337201271631452200225985103634847675073080771865292899559853658;
    uint256 public constant IC7_Y =
        666929653679959575963153451919672454385884334407140677438560707186864020793;
    uint256 public constant IC8_X =
        9070089129424779709490579615695457471602812153829300995603917423522573679304;
    uint256 public constant IC8_Y =
        17684365281246149964276197957958507506565160973342146516702270726191456662661;
    uint256 public constant IC9_X =
        836638753976398753274413443714102274601158488739848679325459931287364491924;
    uint256 public constant IC9_Y =
        19375690491834312258055589469822524844531482482562596375254666834766634057830;
    uint256 public constant IC10_X =
        6292833013852126674764158935715498642905694989861491577850979420349048772789;
    uint256 public constant IC10_Y =
        13409772336890183642226103785180191956685984344674830684276872365137657095622;
    uint256 public constant IC11_X =
        10540387588115769257063713180101262160300680811911062652185945354209410920002;
    uint256 public constant IC11_Y =
        18918667340200873696315401965514755689441065942430823923029210049307323044001;
    uint256 public constant IC12_X =
        12662736796222354302380333756191869009721869104156172051881503441718134464513;
    uint256 public constant IC12_Y =
        17645243980102748830922128083287591865512429374976835360635966386941909837038;
    uint256 public constant IC13_X =
        5537595281273086612165493247966000804445315023604252104629349984489703156329;
    uint256 public constant IC13_Y =
        5785880480311721362081731984162855203270531888247865261372449263383130437013;
    uint256 public constant IC14_X =
        4727166853816386972258846512686703611904133697574169336162380667922606408931;
    uint256 public constant IC14_Y =
        10696106817310652179486424623009616631231011084247647838297967164000776687261;
    uint256 public constant IC15_X =
        5210072149697179388616501362210407708591995176199983914403183052110356051214;
    uint256 public constant IC15_Y =
        3788634760423361099556107944690061619056588243819627122771076244455116978308;
    uint256 public constant IC16_X =
        6589698808986715659607298442490239239582613297013973884611486214931050350956;
    uint256 public constant IC16_Y =
        11769758159112178794826693486190336167472499792254856759035367872611106687379;
    uint256 public constant IC17_X =
        10397469187934284770834451234569390140300500196831935922415500882701844521345;
    uint256 public constant IC17_Y =
        936347738627258578061560555406710232780124428730646217759499018565341899861;
    uint256 public constant IC18_X =
        3335236010719465283299589426077398447168642759320593523041492716036248143524;
    uint256 public constant IC18_Y =
        941198663681176065788123773930593253669861957044761533524227963560697923992;
    uint256 public constant IC19_X =
        14164098435699608208643156136243492504036476051901128506562971398414592991464;
    uint256 public constant IC19_Y =
        4107519615172165143026370734761115865320769632981741865080545422950231562154;
    uint256 public constant IC20_X =
        11848456436718016477032119988125674262225603952443955506955115980587930861134;
    uint256 public constant IC20_Y =
        6849810560800517386422306963354311122277321984840955270487928270858164284903;
    uint256 public constant IC21_X =
        1779853930195200698191145814667605636909013129573385185486520199730530643077;
    uint256 public constant IC21_Y =
        19197365218900327541357116705300664529287241328238643574879334093016409322724;
    uint256 public constant IC22_X =
        2239329004484934826860502547860319581207738831403245238145138617813890662828;
    uint256 public constant IC22_Y =
        2719399869980059481149570232189718478004572690883135767232274814868867368581;
    uint256 public constant IC23_X =
        6504072812410026928505735725613335761367710028781050882482229660013832966535;
    uint256 public constant IC23_Y =
        10960306572763974325826335747604439863143851388807223764914053589616028248815;
    uint256 public constant IC24_X =
        5542373137526652118115035542878775039567113212508336008585163256882786666655;
    uint256 public constant IC24_Y =
        18392052717604994253040461824302370477909298853388621188546876231764068683993;
    uint256 public constant IC25_X =
        1007113456955698573258206710915053304062296173321170498733561331475785965403;
    uint256 public constant IC25_Y =
        18695056740343328503600545091699324320173036246322521303677316081699991341740;
    uint256 public constant IC26_X =
        16783222629512705959225526219482731765898703432890111276818507891624220181489;
    uint256 public constant IC26_Y =
        7934311611979940007438687007903330770220524046876377565271767680930997526384;
    uint256 public constant IC27_X =
        15931233011643439842414580540683146546024795694636900094050929713731849403881;
    uint256 public constant IC27_Y =
        2549107818383246569364684086338155722294685567161516576948432812734235159709;
    
    /// @dev memory pointer sizes
    uint16 public constant P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE = 128;
    uint16 public constant P_TOTAL_SIZE = 896;

    function verifyProof(
        uint256[2] memory pointA_,
        uint256[2][2] memory pointB_,
        uint256[2] memory pointC_,
        uint256[27] memory publicSignals_
    ) public view returns (bool verified_) {
        assembly {
            function checkField(signal_) -> res_ {
                res_ := lt(signal_, SCALAR_FIELD_SIZE)
            }

            function g1MulAdd(pR_, x_, y_, s_) -> res_ {
                let pointer_ := mload(64) // free pointer

                mstore(pointer_, x_)
                mstore(add(pointer_, 32), y_)
                mstore(add(pointer_, 64), s_)

                res_ := staticcall(6000, 7, pointer_, 96, pointer_, 64) // ecMul
                res_ := and(res_, gt(returndatasize(), 0)) // check that multiplication succeeded

                if iszero(res_) {
                    leave
                }

                mstore(add(pointer_, 64), mload(pR_))
                mstore(add(pointer_, 96), mload(add(pR_, 32)))

                res_ := staticcall(150, 6, pointer_, 128, pR_, 64) // ecAdd
                res_ := and(res_, gt(returndatasize(), 0)) // check that addition succeeded
            }

            function checkPairing(pA_, pB_, pC_, pubSignals_, pointer_) -> res_ {
                let pPairing_ := add(pointer_, P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE)

                mstore(pointer_, IC0_X)
                mstore(add(pointer_, 32), IC0_Y)

                /// @dev compute the linear combination of public signals
                if iszero(g1MulAdd(pointer_, IC1_X, IC1_Y, mload(add(pubSignals_, 0)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC2_X, IC2_Y, mload(add(pubSignals_, 32)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC3_X, IC3_Y, mload(add(pubSignals_, 64)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC4_X, IC4_Y, mload(add(pubSignals_, 96)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC5_X, IC5_Y, mload(add(pubSignals_, 128)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC6_X, IC6_Y, mload(add(pubSignals_, 160)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC7_X, IC7_Y, mload(add(pubSignals_, 192)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC8_X, IC8_Y, mload(add(pubSignals_, 224)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC9_X, IC9_Y, mload(add(pubSignals_, 256)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC10_X, IC10_Y, mload(add(pubSignals_, 288)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC11_X, IC11_Y, mload(add(pubSignals_, 320)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC12_X, IC12_Y, mload(add(pubSignals_, 352)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC13_X, IC13_Y, mload(add(pubSignals_, 384)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC14_X, IC14_Y, mload(add(pubSignals_, 416)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC15_X, IC15_Y, mload(add(pubSignals_, 448)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC16_X, IC16_Y, mload(add(pubSignals_, 480)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC17_X, IC17_Y, mload(add(pubSignals_, 512)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC18_X, IC18_Y, mload(add(pubSignals_, 544)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC19_X, IC19_Y, mload(add(pubSignals_, 576)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC20_X, IC20_Y, mload(add(pubSignals_, 608)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC21_X, IC21_Y, mload(add(pubSignals_, 640)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC22_X, IC22_Y, mload(add(pubSignals_, 672)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC23_X, IC23_Y, mload(add(pubSignals_, 704)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC24_X, IC24_Y, mload(add(pubSignals_, 736)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC25_X, IC25_Y, mload(add(pubSignals_, 768)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC26_X, IC26_Y, mload(add(pubSignals_, 800)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC27_X, IC27_Y, mload(add(pubSignals_, 832)))) {
                    leave
                }
                
                /// @dev -A
                mstore(pPairing_, mload(pA_))
                mstore(
                    add(pPairing_, 32),
                    mod(sub(BASE_FIELD_SIZE, mload(add(pA_, 32))), BASE_FIELD_SIZE)
                )

                /// @dev B
                mstore(add(pPairing_, 64), mload(mload(pB_)))
                mstore(add(pPairing_, 96), mload(add(mload(pB_), 32)))
                mstore(add(pPairing_, 128), mload(mload(add(pB_, 32))))
                mstore(add(pPairing_, 160), mload(add(mload(add(pB_, 32)), 32)))

                /// @dev alpha1
                mstore(add(pPairing_, 192), ALPHA_X)
                mstore(add(pPairing_, 224), ALPHA_Y)

                /// @dev beta2
                mstore(add(pPairing_, 256), BETA_X1)
                mstore(add(pPairing_, 288), BETA_X2)
                mstore(add(pPairing_, 320), BETA_Y1)
                mstore(add(pPairing_, 352), BETA_Y2)

                /// @dev public signals
                mstore(add(pPairing_, 384), mload(pointer_))
                mstore(add(pPairing_, 416), mload(add(pointer_, 32)))

                /// @dev gamma2
                mstore(add(pPairing_, 448), GAMMA_X1)
                mstore(add(pPairing_, 480), GAMMA_X2)
                mstore(add(pPairing_, 512), GAMMA_Y1)
                mstore(add(pPairing_, 544), GAMMA_Y2)

                /// @dev C
                mstore(add(pPairing_, 576), mload(pC_))
                mstore(add(pPairing_, 608), mload(add(pC_, 32)))

                /// @dev delta2
                mstore(add(pPairing_, 640), DELTA_X1)
                mstore(add(pPairing_, 672), DELTA_X2)
                mstore(add(pPairing_, 704), DELTA_Y1)
                mstore(add(pPairing_, 736), DELTA_Y2)

                res_ := staticcall(181000, 8, pPairing_, 768, pPairing_, 32) // ecPairing
                res_ := and(res_, mload(pPairing_)) // check that pairing succeeded
            }

            let pointer_ := mload(64) // free pointer
            mstore(64, add(pointer_, P_TOTAL_SIZE))

            /// @dev check that all public signals are in F
            verified_ := 1
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 0))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 32))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 64))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 96))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 128))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 160))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 192))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 224))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 256))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 288))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 320))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 352))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 384))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 416))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 448))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 480))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 512))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 544))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 576))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 608))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 640))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 672))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 704))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 736))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 768))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 800))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 832))))
            
            /// @dev check pairings
            if not(iszero(verified_)) {
                verified_ := checkPairing(pointA_, pointB_, pointC_, publicSignals_, pointer_)
            }
        }
    }
}
