// SPDX-License-Identifier: MIT

/* AUTOGENERATED FILE BY HARDHAT-ZKIT. DO NOT EDIT. */

pragma solidity >=0.7.0 <0.9.0;

contract RevokeEmployeeDataGroth16Verifier {
    // @dev scalar field size
    uint256 public constant SCALAR_FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    /// @dev base field size
    uint256 public constant BASE_FIELD_SIZE =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev verification key data
    uint256 public constant ALPHA_X =
        20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 public constant ALPHA_Y =
        9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 public constant BETA_X1 =
        4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 public constant BETA_X2 =
        6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 public constant BETA_Y1 =
        21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 public constant BETA_Y2 =
        10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 public constant GAMMA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant GAMMA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant GAMMA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant GAMMA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 public constant DELTA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant DELTA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant DELTA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant DELTA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;

    uint256 public constant IC0_X =
        21263602817638885765424385051994976866351608066947184374740408096281951563085;
    uint256 public constant IC0_Y =
        8631080980140704805179999556032181647306518671319578863014314814355394244426;
    uint256 public constant IC1_X =
        19160864171156337131295128923512008029447477748479938397824300824883575323507;
    uint256 public constant IC1_Y =
        6614446701119960902372360320962506326365787635978395882208005669286984353069;
    uint256 public constant IC2_X =
        1358905799631396227907660827706195212512117696446545954305006580988721505836;
    uint256 public constant IC2_Y =
        21355709178024099833546932689635897373388163841749494973597076437941940686093;
    uint256 public constant IC3_X =
        1194247311907507197649111304901215443963020183276277126382681981749371146993;
    uint256 public constant IC3_Y =
        5196381611801317749183303357903129939262550692045410703553966868968109597911;
    uint256 public constant IC4_X =
        14943514266560692414625747625031796427312943137396355179764586532100727682123;
    uint256 public constant IC4_Y =
        4500348067989111462048341011305078468639988384821924834832817547606606821397;
    uint256 public constant IC5_X =
        11077836619915250021356770353735065052407557081570787539541717765585717342364;
    uint256 public constant IC5_Y =
        9610854030021413189946131517707978974352589349635766008979510565542799801464;
    uint256 public constant IC6_X =
        3350910886128535584121442922562117708134808325846898705756039269618577534380;
    uint256 public constant IC6_Y =
        10737809470002752495196182185854090335466795957327575444688896709186930709757;
    uint256 public constant IC7_X =
        12241248092558692510428850338968530130398871167910302895177361996401268346;
    uint256 public constant IC7_Y =
        3672006605565954834895165805481593181227406284720685379867830969021693373398;
    uint256 public constant IC8_X =
        3573626949328744288539174280869461556533985152949002188556093107498929937930;
    uint256 public constant IC8_Y =
        13772041726025323792237641930084166605133881811922963730958245917865891506262;
    uint256 public constant IC9_X =
        8557628383846150716324445235059352564999938870488875647727993242796816655234;
    uint256 public constant IC9_Y =
        20671067053719501356935460034939275017731870876710014977351711763450385521971;
    uint256 public constant IC10_X =
        8498646951078206621572803847950980736128464716568689127244390977128424108968;
    uint256 public constant IC10_Y =
        10438937404686369814930136623625507110712711824619187328603125030237614768124;
    uint256 public constant IC11_X =
        13956413027444192462834380877626289259124113100913613411423758946015378637323;
    uint256 public constant IC11_Y =
        8348171219996045335207611239852457438337419855645923476445245524710093994747;
    uint256 public constant IC12_X =
        11269312775228703673708022259718272601075915312282783775946907496598650539970;
    uint256 public constant IC12_Y =
        17245829675445381939938911095458473889494822118276269983266979573645973125153;
    uint256 public constant IC13_X =
        2636860042878259118100231182326669102971251065984863836280164623157934158586;
    uint256 public constant IC13_Y =
        9148205737809822861362666517531554402752977740921853724626222652262193129688;
    uint256 public constant IC14_X =
        7358941126689279142940131893512102923951082229798747560706089853713984182984;
    uint256 public constant IC14_Y =
        16467537044389693129717882613493126148962614554463374161254265258005696316991;
    uint256 public constant IC15_X =
        10877095265012274359192343160231702427922544582473832481145375884261325737539;
    uint256 public constant IC15_Y =
        5596273296976652487982088141167126520832342361598690330590877358861966137683;
    uint256 public constant IC16_X =
        5668268110698890300784233353616239438130105870436885584248172257362559344968;
    uint256 public constant IC16_Y =
        10729083848861714347665737183437892649686894880510917606901849361850936699388;
    uint256 public constant IC17_X =
        12928206310690193818527020902124844899399382460869637397848878291774123093155;
    uint256 public constant IC17_Y =
        13060775827883449236710104762799897736879902522817983344150731116792418484813;
    uint256 public constant IC18_X =
        8572031602415637848664786468729838660242357461607752259409365366640376020384;
    uint256 public constant IC18_Y =
        15672304029769877111434223376025302086233734381288684955609977318004555308857;
    uint256 public constant IC19_X =
        3396841468455090731280249795647833913407156339100921616771452739935041284240;
    uint256 public constant IC19_Y =
        3495386577733069235607816911102535984244288612247810643737569989137944381675;
    uint256 public constant IC20_X =
        5366138062119468905782467362672923188390056418948575882138296351365839233367;
    uint256 public constant IC20_Y =
        4920693822287828035960268681493895354381054368011092278372431316316155896023;
    uint256 public constant IC21_X =
        17649697875044239688554035287448124559286271444231468710344031618229401780734;
    uint256 public constant IC21_Y =
        17169731488694490228481114171897949476430852628581113864598591514580455803341;
    uint256 public constant IC22_X =
        2034911754418025313848832738583864622616407783414558441373297906460269463702;
    uint256 public constant IC22_Y =
        13817620730619951606557221716398841604354615408560418961252036399405858143405;
    
    /// @dev memory pointer sizes
    uint16 public constant P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE = 128;
    uint16 public constant P_TOTAL_SIZE = 896;

    function verifyProof(
        uint256[2] memory pointA_,
        uint256[2][2] memory pointB_,
        uint256[2] memory pointC_,
        uint256[22] memory publicSignals_
    ) public view returns (bool verified_) {
        assembly {
            function checkField(signal_) -> res_ {
                res_ := lt(signal_, SCALAR_FIELD_SIZE)
            }

            function g1MulAdd(pR_, x_, y_, s_) -> res_ {
                let pointer_ := mload(64) // free pointer

                mstore(pointer_, x_)
                mstore(add(pointer_, 32), y_)
                mstore(add(pointer_, 64), s_)

                res_ := staticcall(6000, 7, pointer_, 96, pointer_, 64) // ecMul
                res_ := and(res_, gt(returndatasize(), 0)) // check that multiplication succeeded

                if iszero(res_) {
                    leave
                }

                mstore(add(pointer_, 64), mload(pR_))
                mstore(add(pointer_, 96), mload(add(pR_, 32)))

                res_ := staticcall(150, 6, pointer_, 128, pR_, 64) // ecAdd
                res_ := and(res_, gt(returndatasize(), 0)) // check that addition succeeded
            }

            function checkPairing(pA_, pB_, pC_, pubSignals_, pointer_) -> res_ {
                let pPairing_ := add(pointer_, P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE)

                mstore(pointer_, IC0_X)
                mstore(add(pointer_, 32), IC0_Y)

                /// @dev compute the linear combination of public signals
                if iszero(g1MulAdd(pointer_, IC1_X, IC1_Y, mload(add(pubSignals_, 0)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC2_X, IC2_Y, mload(add(pubSignals_, 32)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC3_X, IC3_Y, mload(add(pubSignals_, 64)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC4_X, IC4_Y, mload(add(pubSignals_, 96)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC5_X, IC5_Y, mload(add(pubSignals_, 128)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC6_X, IC6_Y, mload(add(pubSignals_, 160)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC7_X, IC7_Y, mload(add(pubSignals_, 192)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC8_X, IC8_Y, mload(add(pubSignals_, 224)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC9_X, IC9_Y, mload(add(pubSignals_, 256)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC10_X, IC10_Y, mload(add(pubSignals_, 288)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC11_X, IC11_Y, mload(add(pubSignals_, 320)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC12_X, IC12_Y, mload(add(pubSignals_, 352)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC13_X, IC13_Y, mload(add(pubSignals_, 384)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC14_X, IC14_Y, mload(add(pubSignals_, 416)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC15_X, IC15_Y, mload(add(pubSignals_, 448)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC16_X, IC16_Y, mload(add(pubSignals_, 480)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC17_X, IC17_Y, mload(add(pubSignals_, 512)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC18_X, IC18_Y, mload(add(pubSignals_, 544)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC19_X, IC19_Y, mload(add(pubSignals_, 576)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC20_X, IC20_Y, mload(add(pubSignals_, 608)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC21_X, IC21_Y, mload(add(pubSignals_, 640)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC22_X, IC22_Y, mload(add(pubSignals_, 672)))) {
                    leave
                }
                
                /// @dev -A
                mstore(pPairing_, mload(pA_))
                mstore(
                    add(pPairing_, 32),
                    mod(sub(BASE_FIELD_SIZE, mload(add(pA_, 32))), BASE_FIELD_SIZE)
                )

                /// @dev B
                mstore(add(pPairing_, 64), mload(mload(pB_)))
                mstore(add(pPairing_, 96), mload(add(mload(pB_), 32)))
                mstore(add(pPairing_, 128), mload(mload(add(pB_, 32))))
                mstore(add(pPairing_, 160), mload(add(mload(add(pB_, 32)), 32)))

                /// @dev alpha1
                mstore(add(pPairing_, 192), ALPHA_X)
                mstore(add(pPairing_, 224), ALPHA_Y)

                /// @dev beta2
                mstore(add(pPairing_, 256), BETA_X1)
                mstore(add(pPairing_, 288), BETA_X2)
                mstore(add(pPairing_, 320), BETA_Y1)
                mstore(add(pPairing_, 352), BETA_Y2)

                /// @dev public signals
                mstore(add(pPairing_, 384), mload(pointer_))
                mstore(add(pPairing_, 416), mload(add(pointer_, 32)))

                /// @dev gamma2
                mstore(add(pPairing_, 448), GAMMA_X1)
                mstore(add(pPairing_, 480), GAMMA_X2)
                mstore(add(pPairing_, 512), GAMMA_Y1)
                mstore(add(pPairing_, 544), GAMMA_Y2)

                /// @dev C
                mstore(add(pPairing_, 576), mload(pC_))
                mstore(add(pPairing_, 608), mload(add(pC_, 32)))

                /// @dev delta2
                mstore(add(pPairing_, 640), DELTA_X1)
                mstore(add(pPairing_, 672), DELTA_X2)
                mstore(add(pPairing_, 704), DELTA_Y1)
                mstore(add(pPairing_, 736), DELTA_Y2)

                res_ := staticcall(181000, 8, pPairing_, 768, pPairing_, 32) // ecPairing
                res_ := and(res_, mload(pPairing_)) // check that pairing succeeded
            }

            let pointer_ := mload(64) // free pointer
            mstore(64, add(pointer_, P_TOTAL_SIZE))

            /// @dev check that all public signals are in F
            verified_ := 1
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 0))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 32))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 64))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 96))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 128))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 160))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 192))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 224))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 256))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 288))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 320))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 352))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 384))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 416))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 448))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 480))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 512))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 544))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 576))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 608))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 640))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 672))))
            
            /// @dev check pairings
            if not(iszero(verified_)) {
                verified_ := checkPairing(pointA_, pointB_, pointC_, publicSignals_, pointer_)
            }
        }
    }
}
