// SPDX-License-Identifier: MIT

/* AUTOGENERATED FILE BY HARDHAT-ZKIT. DO NOT EDIT. */

pragma solidity >=0.7.0 <0.9.0;

contract VaultWithdrawalCircuitGroth16Verifier {
    // @dev scalar field size
    uint256 public constant SCALAR_FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    /// @dev base field size
    uint256 public constant BASE_FIELD_SIZE =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev verification key data
    uint256 public constant ALPHA_X =
        20491192805390485299153009773594534940189261866228447918068658471970481763042;
    uint256 public constant ALPHA_Y =
        9383485363053290200918347156157836566562967994039712273449902621266178545958;
    uint256 public constant BETA_X1 =
        4252822878758300859123897981450591353533073413197771768651442665752259397132;
    uint256 public constant BETA_X2 =
        6375614351688725206403948262868962793625744043794305715222011528459656738731;
    uint256 public constant BETA_Y1 =
        21847035105528745403288232691147584728191162732299865338377159692350059136679;
    uint256 public constant BETA_Y2 =
        10505242626370262277552901082094356697409835680220590971873171140371331206856;
    uint256 public constant GAMMA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant GAMMA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant GAMMA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant GAMMA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 public constant DELTA_X1 =
        11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 public constant DELTA_X2 =
        10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 public constant DELTA_Y1 =
        4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 public constant DELTA_Y2 =
        8495653923123431417604973247489272438418190587263600148770280649306958101930;

    uint256 public constant IC0_X =
        14345614349352049865476069373423302956367230285008406973975668452280001213606;
    uint256 public constant IC0_Y =
        13120345477803837959995794457348163805733052432820764437407376464119413614064;
    uint256 public constant IC1_X =
        5374676242039805049121285761235798259894754474803801674661270061987654502923;
    uint256 public constant IC1_Y =
        16264007136854666111657367237459148503393820527368621788887321456626673653889;
    uint256 public constant IC2_X =
        17766037070649384424111080810214663103178391545043878633163129974647457007811;
    uint256 public constant IC2_Y =
        18241149137957580911135955717044664630071157978187802368368649751869094299382;
    uint256 public constant IC3_X =
        1889015713030543490327681470205242164442603499355313519078081419757153008377;
    uint256 public constant IC3_Y =
        10105372277969162109702906127468379915459458815956299699306877666671018356645;
    uint256 public constant IC4_X =
        2617034694220134724747050066256614384524326503204689633875480455930527539016;
    uint256 public constant IC4_Y =
        21214965592546981405015214757427127117629328596539737372564485872268505552266;
    uint256 public constant IC5_X =
        13246625666218840984005087936844529105403125914257559522469650470644260214675;
    uint256 public constant IC5_Y =
        19114417533430933814815555340849715933121736524495243247871044355418556774938;
    uint256 public constant IC6_X =
        1854885052360029905581679852445208571397868838965108169571229762196642528330;
    uint256 public constant IC6_Y =
        2070080028653199377607007944330117481449983149544766875031425277945025570877;
    uint256 public constant IC7_X =
        4526534590040961286322500700431468731445077577749821149835615885002278470595;
    uint256 public constant IC7_Y =
        5942748625913109659283632383392887224874529167038946042810512593133177459676;
    uint256 public constant IC8_X =
        5046535029739261318776142669633097603719880710261051611219014077618155957407;
    uint256 public constant IC8_Y =
        2111579810646030709161145525521173517553513689102455806373220034280210433160;
    uint256 public constant IC9_X =
        6221524121044146768463408619614287048960444779633597859899136968058046698231;
    uint256 public constant IC9_Y =
        8447549001758636718510564429769862085071878424449889953950449051640242019811;
    uint256 public constant IC10_X =
        10016999406584981525642231369925642404558104956092497833741014907041226853592;
    uint256 public constant IC10_Y =
        8117464936263667365856980887212590159393368326733197920667771844366219175428;
    uint256 public constant IC11_X =
        3090348994823924137616788367670158451042539768539429938861204873674595642234;
    uint256 public constant IC11_Y =
        14266860384653229811766737124895199739159635579366127347520843202060845129554;
    uint256 public constant IC12_X =
        9382610844920877860873513721140209257006178802649743944956502541573209897027;
    uint256 public constant IC12_Y =
        12618755078819645181688012792639783208387092203152245497328270949136016781408;
    uint256 public constant IC13_X =
        18657595200287913791972525972343493497664416602160206885287400686015922158088;
    uint256 public constant IC13_Y =
        12992703372652822354510941093741074236459180688197586263038112744445046575332;
    uint256 public constant IC14_X =
        20979894903290965108861919361942986726535197573259704027599529089407136674700;
    uint256 public constant IC14_Y =
        13743985935061864363032081415399528554207121548438482056281265195728885068502;
    uint256 public constant IC15_X =
        13968037919121731503513049077879964843301755028989090791419323409039716765801;
    uint256 public constant IC15_Y =
        5825248105414277204384109361017968927516470785122916830522981973183835299071;
    uint256 public constant IC16_X =
        10468731031475723339464775206258476496009282417668096089836696435988926671260;
    uint256 public constant IC16_Y =
        10632747321877171987318660350622119201242885521324560357099237780405764634941;
    uint256 public constant IC17_X =
        6370932313847772673496740132965144823222364700153730357841124088075473542037;
    uint256 public constant IC17_Y =
        20405861192364806489834692779400015833972093834355797593329558913338138820343;
    uint256 public constant IC18_X =
        13779583240479032804717851333770899164873409130848375955938477427911336843358;
    uint256 public constant IC18_Y =
        2688227096959147994567480311612883599379033206121368231348609062274563559883;
    uint256 public constant IC19_X =
        20594313738314185787442273748827442947975693122609499221823629873755187640637;
    uint256 public constant IC19_Y =
        18952755337574637020328204916993986976425508054770742764504112253429928104609;
    uint256 public constant IC20_X =
        15998613387697934979911355639008302489355543559341535887346853805929917598785;
    uint256 public constant IC20_Y =
        1791428409002507298292209328593113688224176470698000798170457379856459006494;
    uint256 public constant IC21_X =
        16292960102139936547883455258464409497720883236341597128865735874379315624669;
    uint256 public constant IC21_Y =
        5045642841457469953529195829064734074894550770284680004302712834590575148180;
    uint256 public constant IC22_X =
        5707854839405856023219575158378420499077381120323012350493650975642104248478;
    uint256 public constant IC22_Y =
        19644125939862436221114734971877416776263375362945225274057287852274849962524;
    uint256 public constant IC23_X =
        15459276797839075193485096316314647331024519379740284177058220587887389449738;
    uint256 public constant IC23_Y =
        11343529268052088493943735037021020959288801143771269951171924174861913739101;
    uint256 public constant IC24_X =
        8144072074574538964639681955010102294379452680008470877898935227817680281404;
    uint256 public constant IC24_Y =
        15264831735254414946336557366825045168666106053416326445514268622130916984791;
    uint256 public constant IC25_X =
        19116876351220134335442400728163946316517886692948453665665241939571149096390;
    uint256 public constant IC25_Y =
        7490722363270363270333286011485291476056113010406833274397400401965865765267;
    uint256 public constant IC26_X =
        11150352863904202498611711718583741778048426048223124836125026325197002683256;
    uint256 public constant IC26_Y =
        7776107419898953219726105512997126626061000191379045968598724774582020670468;
    uint256 public constant IC27_X =
        2374102330882096842401865313465686934197292399952928950860957777124566739524;
    uint256 public constant IC27_Y =
        8964008199977604173261270518793063739046321835476262304036201655780709870590;
    uint256 public constant IC28_X =
        12207216405171396176768416713171931768842845835414894757078741732741384757103;
    uint256 public constant IC28_Y =
        10762131246570943460315365937519465568247167127204902336179463663368378790811;
    uint256 public constant IC29_X =
        13971921347917478821039088180960216913516708757766301599457475214365642247132;
    uint256 public constant IC29_Y =
        6403577851871398618867288795839244242418906283240351426427584630346413500362;
    uint256 public constant IC30_X =
        7158097564025749248950654444880296102273035994088908689208095336082696215114;
    uint256 public constant IC30_Y =
        174632843781296047329487498164363191037480491436204506081523426601806370460;
    uint256 public constant IC31_X =
        2153446643922454133170821365485159533164754352078286548059815794632083866838;
    uint256 public constant IC31_Y =
        19948481766760457032209940001799207397783033950787681190345658432608885075045;
    uint256 public constant IC32_X =
        12948617305421227734642182056182977714756954818168314427564417074458776914435;
    uint256 public constant IC32_Y =
        16764874822799326900861837051111177973652115828506440479333009144027380640196;
    uint256 public constant IC33_X =
        18195957933958804446010301948899793834154588585875495428242858202153048263490;
    uint256 public constant IC33_Y =
        20780754098036390624598731652522250614478657187059339223436681735562083073754;
    uint256 public constant IC34_X =
        15271007863637610879231012317814293697695640311111731218732115594811406179055;
    uint256 public constant IC34_Y =
        13156185805228701243956852284854725353590341651417125167645420498459707509480;
    uint256 public constant IC35_X =
        11363998537903065661694287413534092403511685689119722036279131406005520727378;
    uint256 public constant IC35_Y =
        1788490078857224810952962078028459967450656578117107209210194049758347695672;
    uint256 public constant IC36_X =
        9445434559286955171028967751506960212687930821203787948332552136284664100063;
    uint256 public constant IC36_Y =
        8752541704080785336799768580071431408689351859357713359645031655298033379579;
    uint256 public constant IC37_X =
        4359385442350485292275297956380362407404526627018213713259691072946860454540;
    uint256 public constant IC37_Y =
        20594864367459722548669207612187595189422985607643463893606674098766699164776;
    uint256 public constant IC38_X =
        21170462818751612321241865072361528548009054847612427581435740215654705732159;
    uint256 public constant IC38_Y =
        3647537087052348107078323549593394045920162781711447440936673280952798457303;
    uint256 public constant IC39_X =
        15168334711888587322375660523366819991425243165071172033847239682859014005820;
    uint256 public constant IC39_Y =
        4221662744487428581873833843206234535183334742714881345251160291745938001504;
    uint256 public constant IC40_X =
        19298079050979888266795181172717955909175001433908327943422560130791726322352;
    uint256 public constant IC40_Y =
        7284940539234870184412751548205624394913848733255319366175729190688816811159;
    uint256 public constant IC41_X =
        6620452303079574461102196655436847118650880971313961648708251524334396901001;
    uint256 public constant IC41_Y =
        13638652306596407215374633514755206204437347124359686441902369519184651882816;
    uint256 public constant IC42_X =
        18528358319752435757702971114205937036236093119347913108669348056389193418875;
    uint256 public constant IC42_Y =
        4358997788250588089672558658869451896727767411156330270590904565127779639470;
    uint256 public constant IC43_X =
        5196876646885838474641367840162861904616917762715229486407865682571169351893;
    uint256 public constant IC43_Y =
        9634660502112366390364613317830912423043601690172530690928842407457093647242;
    uint256 public constant IC44_X =
        15799388702664702153860998947212233477672930642583094711078526963255613129919;
    uint256 public constant IC44_Y =
        4895332272390363618234234719477219353913681460520891179273287213427202830834;
    uint256 public constant IC45_X =
        10752488128231096410391508496188708706435789405772525624379139485823527952619;
    uint256 public constant IC45_Y =
        21693089146638532484999857493012641447012003616508228027374332592645632695097;
    uint256 public constant IC46_X =
        1698611778829181876792450202242972464599717147582566300818004263269502479146;
    uint256 public constant IC46_Y =
        15761124602930589223841287753488848710435228624161173227917325732476021678543;
    uint256 public constant IC47_X =
        20949060035773594332198757578927996751943763453646208252525446183572366406986;
    uint256 public constant IC47_Y =
        13737223837330272441241670594808030792465994127674690864464737339411896741471;
    uint256 public constant IC48_X =
        21659998571079544904191742382248874429183282440614164188026651381296939881501;
    uint256 public constant IC48_Y =
        9817245224478506666073150756637570273457045895290638333872279857211563411337;
    uint256 public constant IC49_X =
        15197174582205816376150077846763075691226917029378982780259893720947599101939;
    uint256 public constant IC49_Y =
        9811775784890190625944263340846717967242831658286535543972055450553523455707;
    uint256 public constant IC50_X =
        17596309027940618948463566380221574162986638582292809848784860369231592077959;
    uint256 public constant IC50_Y =
        6714986274590811212378624804331059973723154336674486856394844551524385557891;
    
    /// @dev memory pointer sizes
    uint16 public constant P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE = 128;
    uint16 public constant P_TOTAL_SIZE = 896;

    function verifyProof(
        uint256[2] memory pointA_,
        uint256[2][2] memory pointB_,
        uint256[2] memory pointC_,
        uint256[50] memory publicSignals_
    ) public view returns (bool verified_) {
        assembly {
            function checkField(signal_) -> res_ {
                res_ := lt(signal_, SCALAR_FIELD_SIZE)
            }

            function g1MulAdd(pR_, x_, y_, s_) -> res_ {
                let pointer_ := mload(64) // free pointer

                mstore(pointer_, x_)
                mstore(add(pointer_, 32), y_)
                mstore(add(pointer_, 64), s_)

                res_ := staticcall(6000, 7, pointer_, 96, pointer_, 64) // ecMul
                res_ := and(res_, gt(returndatasize(), 0)) // check that multiplication succeeded

                if iszero(res_) {
                    leave
                }

                mstore(add(pointer_, 64), mload(pR_))
                mstore(add(pointer_, 96), mload(add(pR_, 32)))

                res_ := staticcall(150, 6, pointer_, 128, pR_, 64) // ecAdd
                res_ := and(res_, gt(returndatasize(), 0)) // check that addition succeeded
            }

            function checkPairing(pA_, pB_, pC_, pubSignals_, pointer_) -> res_ {
                let pPairing_ := add(pointer_, P_PUBLIC_SIGNALS_ACCUMULATOR_SIZE)

                mstore(pointer_, IC0_X)
                mstore(add(pointer_, 32), IC0_Y)

                /// @dev compute the linear combination of public signals
                if iszero(g1MulAdd(pointer_, IC1_X, IC1_Y, mload(add(pubSignals_, 0)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC2_X, IC2_Y, mload(add(pubSignals_, 32)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC3_X, IC3_Y, mload(add(pubSignals_, 64)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC4_X, IC4_Y, mload(add(pubSignals_, 96)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC5_X, IC5_Y, mload(add(pubSignals_, 128)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC6_X, IC6_Y, mload(add(pubSignals_, 160)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC7_X, IC7_Y, mload(add(pubSignals_, 192)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC8_X, IC8_Y, mload(add(pubSignals_, 224)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC9_X, IC9_Y, mload(add(pubSignals_, 256)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC10_X, IC10_Y, mload(add(pubSignals_, 288)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC11_X, IC11_Y, mload(add(pubSignals_, 320)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC12_X, IC12_Y, mload(add(pubSignals_, 352)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC13_X, IC13_Y, mload(add(pubSignals_, 384)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC14_X, IC14_Y, mload(add(pubSignals_, 416)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC15_X, IC15_Y, mload(add(pubSignals_, 448)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC16_X, IC16_Y, mload(add(pubSignals_, 480)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC17_X, IC17_Y, mload(add(pubSignals_, 512)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC18_X, IC18_Y, mload(add(pubSignals_, 544)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC19_X, IC19_Y, mload(add(pubSignals_, 576)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC20_X, IC20_Y, mload(add(pubSignals_, 608)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC21_X, IC21_Y, mload(add(pubSignals_, 640)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC22_X, IC22_Y, mload(add(pubSignals_, 672)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC23_X, IC23_Y, mload(add(pubSignals_, 704)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC24_X, IC24_Y, mload(add(pubSignals_, 736)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC25_X, IC25_Y, mload(add(pubSignals_, 768)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC26_X, IC26_Y, mload(add(pubSignals_, 800)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC27_X, IC27_Y, mload(add(pubSignals_, 832)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC28_X, IC28_Y, mload(add(pubSignals_, 864)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC29_X, IC29_Y, mload(add(pubSignals_, 896)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC30_X, IC30_Y, mload(add(pubSignals_, 928)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC31_X, IC31_Y, mload(add(pubSignals_, 960)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC32_X, IC32_Y, mload(add(pubSignals_, 992)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC33_X, IC33_Y, mload(add(pubSignals_, 1024)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC34_X, IC34_Y, mload(add(pubSignals_, 1056)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC35_X, IC35_Y, mload(add(pubSignals_, 1088)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC36_X, IC36_Y, mload(add(pubSignals_, 1120)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC37_X, IC37_Y, mload(add(pubSignals_, 1152)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC38_X, IC38_Y, mload(add(pubSignals_, 1184)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC39_X, IC39_Y, mload(add(pubSignals_, 1216)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC40_X, IC40_Y, mload(add(pubSignals_, 1248)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC41_X, IC41_Y, mload(add(pubSignals_, 1280)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC42_X, IC42_Y, mload(add(pubSignals_, 1312)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC43_X, IC43_Y, mload(add(pubSignals_, 1344)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC44_X, IC44_Y, mload(add(pubSignals_, 1376)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC45_X, IC45_Y, mload(add(pubSignals_, 1408)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC46_X, IC46_Y, mload(add(pubSignals_, 1440)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC47_X, IC47_Y, mload(add(pubSignals_, 1472)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC48_X, IC48_Y, mload(add(pubSignals_, 1504)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC49_X, IC49_Y, mload(add(pubSignals_, 1536)))) {
                    leave
                }
                if iszero(g1MulAdd(pointer_, IC50_X, IC50_Y, mload(add(pubSignals_, 1568)))) {
                    leave
                }
                
                /// @dev -A
                mstore(pPairing_, mload(pA_))
                mstore(
                    add(pPairing_, 32),
                    mod(sub(BASE_FIELD_SIZE, mload(add(pA_, 32))), BASE_FIELD_SIZE)
                )

                /// @dev B
                mstore(add(pPairing_, 64), mload(mload(pB_)))
                mstore(add(pPairing_, 96), mload(add(mload(pB_), 32)))
                mstore(add(pPairing_, 128), mload(mload(add(pB_, 32))))
                mstore(add(pPairing_, 160), mload(add(mload(add(pB_, 32)), 32)))

                /// @dev alpha1
                mstore(add(pPairing_, 192), ALPHA_X)
                mstore(add(pPairing_, 224), ALPHA_Y)

                /// @dev beta2
                mstore(add(pPairing_, 256), BETA_X1)
                mstore(add(pPairing_, 288), BETA_X2)
                mstore(add(pPairing_, 320), BETA_Y1)
                mstore(add(pPairing_, 352), BETA_Y2)

                /// @dev public signals
                mstore(add(pPairing_, 384), mload(pointer_))
                mstore(add(pPairing_, 416), mload(add(pointer_, 32)))

                /// @dev gamma2
                mstore(add(pPairing_, 448), GAMMA_X1)
                mstore(add(pPairing_, 480), GAMMA_X2)
                mstore(add(pPairing_, 512), GAMMA_Y1)
                mstore(add(pPairing_, 544), GAMMA_Y2)

                /// @dev C
                mstore(add(pPairing_, 576), mload(pC_))
                mstore(add(pPairing_, 608), mload(add(pC_, 32)))

                /// @dev delta2
                mstore(add(pPairing_, 640), DELTA_X1)
                mstore(add(pPairing_, 672), DELTA_X2)
                mstore(add(pPairing_, 704), DELTA_Y1)
                mstore(add(pPairing_, 736), DELTA_Y2)

                res_ := staticcall(181000, 8, pPairing_, 768, pPairing_, 32) // ecPairing
                res_ := and(res_, mload(pPairing_)) // check that pairing succeeded
            }

            let pointer_ := mload(64) // free pointer
            mstore(64, add(pointer_, P_TOTAL_SIZE))

            /// @dev check that all public signals are in F
            verified_ := 1
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 0))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 32))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 64))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 96))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 128))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 160))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 192))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 224))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 256))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 288))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 320))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 352))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 384))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 416))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 448))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 480))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 512))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 544))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 576))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 608))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 640))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 672))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 704))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 736))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 768))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 800))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 832))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 864))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 896))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 928))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 960))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 992))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1024))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1056))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1088))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1120))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1152))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1184))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1216))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1248))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1280))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1312))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1344))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1376))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1408))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1440))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1472))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1504))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1536))))
            verified_ := and(verified_, checkField(mload(add(publicSignals_, 1568))))
            
            /// @dev check pairings
            if not(iszero(verified_)) {
                verified_ := checkPairing(pointA_, pointB_, pointC_, publicSignals_, pointer_)
            }
        }
    }
}
