name: "CI"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        node-version: [18.x]
        go-version: ["1.22"]

    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: "Install Golang dependencies"
        run: "cd zk && make"

      - name: "Install the dependencies"
        run: "npm install"

      - name: Hardhat coverage
        run: |
          touch eERC-tests.txt && \
          npx hardhat coverage | tee eERC-tests.txt || true && \
          echo '```' ? >> $GITHUB_STEP_SUMMARY && \
          cat eERC-tests.txt >> $GITHUB_STEP_SUMMARY && \
          echo '```' ? >> $GITHUB_STEP_SUMMARY

      - name: "Run linter"
        run: "npm run lint"
